---
published: true
title : "[이것이 자바다] 자바 Reminding(8) - 예외처리"
categories:
  - Java
tags:
  - Study
  - Java
toc: true
toc_sticky: true
sidebar:
    nav: "sidebar-category"
---

#  [11장] 예외처리

## 11.1 예외와 예외 클래스
&nbsp; 컴퓨터 하드웨어의 고장으로 인해 응용프로그램 실행 오류가 발생하는 것을 자바에서는 에러라고 한다. 프로그램을 아무리 견고하게 만들어도 개발자는 이런 에러에 대처할 방법이 전혀 없다. 자바에서는 에러 이외에 예외(exception)라고 부르는 오류가 있다. 예외란 잘못된 사용 또는 코딩으로 인한 오류를 말한다. 예외가 발생되면 프로그램은 곧바로 종료된다는 점에서는 에러와 동일하지만, 예외 처리를 통해 계속 실행 상태를 유지할 수 있다. 예외에는 다음 두가지가 있다.
<br>
<br>

- 일반예외
  > 컴파일러가 예외 처리 코드 여부를 검사하는 예외를 말한다.
- 실행예외
  > 컴파일러가 예외 처리 코드 여부를 검사하지 않는 예외를 말한다.

<br>

자바는 예외가 발생하면 예외 클래스로부터 객체를 생성한다. 이 객체는 예외 처리 시 사용된다. 자바의 모든 에러와 예외 클래스는 Throwable을 상속받아 만들어지고, 추가적으로 에외 클래스는 java.lang.Exception 클래스를 상속받는다.

<br>
<br>


## 11.2 예외 처리 코드
&nbsp; 예외가 발생했을 때 프로그램의 갑작스러운 종료를 막고 정상실행을 유지 할 수 있도록 처리하는 코드를 예외 처리 코드라 한다. 예외 처리 코드는 try-catch-finally 블록으로 구성된다.

```
try{
  
  예외 발생 가능 코드

}catch(예외클래스 e){
  
  예외처리

}finally{

  항상 실행;

}
```

<br>

try 블록에서 작성한 코드가 예외 없이 정상 실행되면 catch 블록은 실행되지 않고 finally 블록이 실행된다. 그러나 try 블록에서 예외가 발생하면 catch 블록이 실행되고 연이어 finally 블록이 실행된다. 예외 발생 여부와 상관없이 finally 블록은 항상 실행된다. 심지어 try 블록과 catch 블록에서 return문을 사용하더라도 finally 블록은 항상 실행된다. finally 블록은 옵션으로 생략 가능하다.


### <center>예외 처리 예제</center>

<br>

```
public class ExceptionHandlingExample1{
  public static void printLength(String data){
    int result = data.length();
    System.out.println("문자 수 : " + result);
  }


  public static void main(String[] args){
    System.out.println("[프로그램 시작]\n");
    printLength("ThisIsJava");  // 문자 수 : 10
    printLength(null);  // NullpointerException 발생
    System.out.println("[프로그램 종료]");
  }
}
```

<br>

위 예제에서 예외 처리 코드를 추가해보자. try 블록에서 NullpointerException이 발생하면 catch 블록을 실행해서 예외를 처리하도록 하고, 예외 발생 여부와 상관없이 fianlly 블록을 실행하여 마무리하자.

<br>


```
public class ExceptionHandlerExample2{
  public static void printLength(String data){
    try{
      int result = data.length();
      System.out.println("문자 수: " = result);
    }catch(NullpointerException e){
      System.out.println(e.getMessage());
      //System.out.println(e.toString());
      //e.printStackTrace();
    }finally{
      Sustem.out.println("[마무리 실행]\n")
    }
  }

  public static void main(String[] args){
    System.out.println("[프로그램 실행]\n");
    printLength("ThisIsJava"); // 문자 수 : 10
    printLength(null); // Cannot invoke "String.length()" because "data" is null 출력
    System.out.println("[프로그램 종료]");    
}
```

<br>


## 11.3 예외 종류에 따른 처리
&nbsp; try 블록에는 다양한 종류의 예제가 발생할 수 있다. 이 경우, 다중 catch를 사용하면 발생하는 예외에 따라 예외 처리 코드를 다르게 작성할 수 있다. catch 블록이 여러개라 할지라도 catch 블록은 단 하나만 실행된다.

<br>

두 개 이 상의 예외를 하나의 catch 블록으로 동일하게 예외 처리하고 싶을 때가 있다. 이 경우에는 catch 블록에 예외 클래스를 기호 | 로 연결하면 된다.

```
catch(NullpointerException | NumberFormatException e)
```

<br>

## 11.4 예외 떠넘기기
&nbsp; 메소드 내부에서 예외가 발생할 때 try-catch 블록으로 예외를 처리하는 것이 기본이지만, 메소드를 호출한 곳으로 예외를 떠넘길 수도 있다. 이때 사용하는 키워드가 throws 이다. throws는 메소드 선언부 끝에 작성하는데, 떠넘길 예외 클래스를 쉼표로 구분해서 나열해주면 된다.

```
리턴타입 메소드명(매개변수...) throws 예외클래스1, 에외클래스2{}
```

throws 키워드가 붙어 있는 메소드에서 해당 예외를 처리하지 않고 떠넘겼기 때문에 이 메소드를 호출하는 곳에서 예외를 받아 처리해야 한다. 에를 들어 다음 코드는 ClassNotFoundException을 throws하는 method2()의 예외를 method1()에서 호출할 때 처리하고 있다.

```
public void method1(){
  try{
    method2();
  }catch(ClassNotFoundException e){
    System.out.println("예외 처리 : " + e.getMessage());

  }

  public void method2() throws ClassNotFoundException{
    Class.forName("java.lang.String2");
  }
}
```

<br>

나열해야 할 예외 클래스가 많을 경우에는 throws Exception 또는 throws Throwable 만으로 모든 예외를 간단히 떠넘길 수도 있다.

<br>

main() 메소드에서도 throws 키워드를 사용해서 예외를 떠넘길 수 있는데, 결국 JVM이 최종적으로 예외 처리를 하게 된다. JVM은 예외의 내용을 콘솔에 출력하는 것으로 예외 처리를 한다.

<br>


## 11.6 사용자 정의 예외
&nbsp; 표준 라이브러리에 존재하지 안흔 예외를 직접 정의해서 사용할수 있다. 이것을 사용자 정의 예외라고 한다.

<br>

### 사용자 정의 예외
&nbsp; 사용자 정의 예외는 컴파일러가 체크하는 일반 예외로 선언할 수도 있고, 컴파일러가 체크하지 않는 실행 예외로 선언할 수도 있다. 통상적으로 일반 예외는 Exception의 자식 클래스로 선언하고, 실행 예외는 RuntimeException의 자식 클래스로 선언한다.

<br>

```
public class xxxException extends [Exception | RuntimeException ]{
  public XXXException(){}

  public XXXException(String message){
    super(message);
  }
}
```

사용자 정의 예외 클래스에는 기본 생성자와 예외 메시지를 입력받는 생성자를 선언해준다. 예외 메시지는 부모 생성자 매개값으로 넘겨주는데, 그 이유는 예외 객체의 공통 메소드인 getMessage()의 리턴값으로 사용하기 위해서이다.

<br>


### 예외 발생 시키기
&nbsp; 자바에서 제공하는 표준 예외뿐만 아니라 사용자 정의 예외를 직접 코드에서 발생시키려면 throw키워드와 함께 예외 객체를 제공하면 된다. 예외의 원인에 해당하는 메시지를 제공하고 싶다면 생성자 매개값으로 전달한다.

```
throw new Exception("예외 메시지")
```




# 마무리
&nbsp; *이것이 자바다* 11장 정리 완료. 코딩하다보면 자주 보이는 예외처리에 관한 설명, 모르는 부분이나 사용자 정의 예제 처럼 생소한 부분들에 관해서는 다시 한번 머리속에 넣어두기!







